imagens = [
    {"nome":"00000001_000.png", "tipos":["Cardiomegaly"]},
    {"nome":"Ak (1).png", "tipos":["Ak"]},    
    {"nome":"Ak (2).png", "tipos":["Ak"]},
    {"nome":"Ak (3).png", "tipos":["Ak"]},
    {"nome":"Ak (4).png", "tipos":["Ak"]},
    {"nome":"Ak (5).png", "tipos":["Ak"]},
    {"nome":"Ak (6).png", "tipos":["Ak"]},
    {"nome":"Ak (7).png", "tipos":["Ak"]},
    {"nome":"Ak (8).png", "tipos":["Ak"]},
    {"nome":"Ak (9).png", "tipos":["Ak"]},
    {"nome":"Ak (10).png", "tipos":["Ak"]},
    {"nome":"Ak (11).png", "tipos":["Ak"]},
    {"nome":"Ak (12).png", "tipos":["Ak"]},
    {"nome":"Ak (13).png", "tipos":["Ak"]},
    {"nome":"Ak (14).png", "tipos":["Ak"]},
    {"nome":"Ak (15).png", "tipos":["Ak"]},
    {"nome":"Ak (16).png", "tipos":["Ak"]},
    {"nome":"Ak (17).png", "tipos":["Ak"]},
    {"nome":"Ak (18).png", "tipos":["Ak"]},
    {"nome":"Ak (19).png", "tipos":["Ak"]},
    {"nome":"Ak (20).png", "tipos":["Ak"]},
    {"nome":"Ak (21).png", "tipos":["Ak"]},
    {"nome":"Ak (22).png", "tipos":["Ak"]},
    {"nome":"Ak (23).png", "tipos":["Ak"]},
    {"nome":"Ak (24).png", "tipos":["Ak"]},
    {"nome":"Ak (25).png", "tipos":["Ak"]},
    {"nome":"Ak (26).png", "tipos":["Ak"]},
    {"nome":"Ak (27).png", "tipos":["Ak"]},
    {"nome":"Ak (28).png", "tipos":["Ak"]},
    {"nome":"Ak (29).png", "tipos":["Ak"]},
    {"nome":"Ak (30).png", "tipos":["Ak"]},
    {"nome":"Ak (31).png", "tipos":["Ak"]},
    {"nome":"Ak (32).png", "tipos":["Ak"]},
    {"nome":"Ak (33).png", "tipos":["Ak"]},
    {"nome":"Ak (34).png", "tipos":["Ak"]},
    {"nome":"Ak (35).png", "tipos":["Ak"]},
    {"nome":"Ak (36).png", "tipos":["Ak"]},
    {"nome":"Ak (37).png", "tipos":["Ak"]},
    {"nome":"Ak (38).png", "tipos":["Ak"]},
    {"nome":"Ak (39).png", "tipos":["Ak"]},
    {"nome":"Ak (40).png", "tipos":["Ak"]},
    {"nome":"Ak (41).png", "tipos":["Ak"]},
    {"nome":"Ak (42).png", "tipos":["Ak"]},
    {"nome":"Ak (43).png", "tipos":["Ak"]},
    {"nome":"Ak (44).png", "tipos":["Ak"]},
    {"nome":"Ak (45).png", "tipos":["Ak"]},
    {"nome":"Ak (46).png", "tipos":["Ak"]},
    {"nome":"Ak (47).png", "tipos":["Ak"]},
    {"nome":"Ak (48).png", "tipos":["Ak"]},
    {"nome":"Ak (49).png", "tipos":["Ak"]},
    {"nome":"Ak (50).png", "tipos":["Ak"]},
    {"nome":"Ak (51).png", "tipos":["Ak"]},
    {"nome":"Ak (52).png", "tipos":["Ak"]},
    {"nome":"Ak (53).png", "tipos":["Ak"]},
    {"nome":"Ak (54).png", "tipos":["Ak"]},
    {"nome":"Ak (55).png", "tipos":["Ak"]},
    {"nome":"Ak (56).png", "tipos":["Ak"]},
    {"nome":"Ak (57).png", "tipos":["Ak"]},
    {"nome":"Ak (58).png", "tipos":["Ak"]},
    {"nome":"Ak (59).png", "tipos":["Ak"]},
    {"nome":"Ak (60).png", "tipos":["Ak"]},
    {"nome":"Ak (61).png", "tipos":["Ak"]},
    {"nome":"Ak (62).png", "tipos":["Ak"]},
    {"nome":"Ak (63).png", "tipos":["Ak"]},
    {"nome":"Ak (64).png", "tipos":["Ak"]},
    {"nome":"Ak (65).png", "tipos":["Ak"]},
    {"nome":"Ak (66).png", "tipos":["Ak"]},
    {"nome":"Ak (67).png", "tipos":["Ak"]},
    {"nome":"Ak (68).png", "tipos":["Ak"]},
    {"nome":"Ak (69).png", "tipos":["Ak"]},
    {"nome":"Ak (70).png", "tipos":["Ak"]},
    {"nome":"Ak (71).png", "tipos":["Ak"]},
    {"nome":"Ak (72).png", "tipos":["Ak"]},
    {"nome":"Ak (73).png", "tipos":["Ak"]},
    {"nome":"Ak (74).png", "tipos":["Ak"]},
    {"nome":"Ak (75).png", "tipos":["Ak"]},
    {"nome":"Ak (76).png", "tipos":["Ak"]},
    {"nome":"Ak (77).png", "tipos":["Ak"]},
    {"nome":"Ak (78).png", "tipos":["Ak"]},
    {"nome":"Ak (79).png", "tipos":["Ak"]},
    {"nome":"Ak (80).png", "tipos":["Ak"]},
    {"nome":"Ak (81).png", "tipos":["Ak"]},
    {"nome":"Ak (82).png", "tipos":["Ak"]},
    {"nome":"Ak (83).png", "tipos":["Ak"]},
    {"nome":"Ak (84).png", "tipos":["Ak"]},
    {"nome":"Ak (85).png", "tipos":["Ak"]},
    {"nome":"Ak (86).png", "tipos":["Ak"]},
    {"nome":"Ak (87).png", "tipos":["Ak"]},
    {"nome":"Ak (88).png", "tipos":["Ak"]},
    {"nome":"Ak (89).png", "tipos":["Ak"]},
    {"nome":"Ak (90).png", "tipos":["Ak"]},
    {"nome":"Ak (91).png", "tipos":["Ak"]},
    {"nome":"Ak (92).png", "tipos":["Ak"]},
    {"nome":"Ak (93).png", "tipos":["Ak"]},
    {"nome":"Ak (94).png", "tipos":["Ak"]},
    {"nome":"Ak (95).png", "tipos":["Ak"]},
    {"nome":"Ak (96).png", "tipos":["Ak"]},
    {"nome":"Ak (97).png", "tipos":["Ak"]},
    {"nome":"Ak (98).png", "tipos":["Ak"]},
    {"nome":"Ak (99).png", "tipos":["Ak"]},
    {"nome":"Ak (100).png", "tipos":["Ak"]},
    {"nome":"Ala_Idris (1).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (2).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (3).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (4).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (5).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (6).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (7).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (8).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (9).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (10).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (11).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (12).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (13).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (14).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (15).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (16).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (17).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (18).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (19).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (20).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (21).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (22).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (23).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (24).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (25).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (26).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (27).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (28).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (29).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (30).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (31).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (32).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (33).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (34).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (35).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (36).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (37).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (38).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (39).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (40).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (41).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (42).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (43).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (44).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (45).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (46).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (47).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (48).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (49).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (50).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (51).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (52).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (53).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (54).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (55).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (56).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (57).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (58).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (59).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (60).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (61).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (62).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (63).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (64).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (65).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (66).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (67).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (68).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (69).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (70).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (71).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (72).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (73).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (74).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (75).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (76).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (77).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (78).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (79).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (80).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (81).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (82).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (83).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (84).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (85).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (86).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (87).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (88).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (89).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (90).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (91).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (92).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (93).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (94).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (95).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (96).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (97).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (98).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (99).png","tipos":["Ala_Idris"]},
    {"nome":"Ala_Idris (100).png","tipos":["Ala_Idris"]},
    {"nome":"Buzgulu (1).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (2).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (3).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (4).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (5).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (6).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (7).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (8).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (9).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (10).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (11).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (12).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (13).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (14).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (15).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (16).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (17).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (18).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (19).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (20).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (21).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (22).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (23).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (24).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (25).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (26).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (27).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (28).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (29).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (30).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (31).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (32).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (33).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (34).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (35).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (36).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (37).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (38).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (39).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (40).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (41).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (42).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (43).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (44).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (45).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (46).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (47).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (48).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (49).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (50).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (51).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (52).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (53).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (54).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (55).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (56).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (57).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (58).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (59).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (60).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (61).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (62).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (63).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (64).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (65).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (66).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (67).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (68).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (69).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (70).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (71).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (72).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (73).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (74).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (75).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (76).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (77).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (78).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (79).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (80).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (81).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (82).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (83).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (84).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (85).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (86).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (87).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (88).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (89).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (90).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (91).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (92).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (93).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (94).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (95).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (96).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (97).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (98).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (99).png","tipos":["Buzgulu"]},
    {"nome":"Buzgulu (100).png","tipos":["Buzgulu"]},
    {"nome":"Dimnit (1).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (2).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (3).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (4).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (5).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (6).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (7).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (8).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (9).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (10).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (11).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (12).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (13).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (14).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (15).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (16).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (17).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (18).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (19).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (20).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (21).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (22).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (23).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (24).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (25).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (26).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (27).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (28).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (29).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (30).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (31).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (32).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (33).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (34).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (35).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (36).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (37).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (38).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (39).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (40).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (41).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (42).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (43).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (44).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (45).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (46).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (47).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (48).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (49).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (50).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (51).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (52).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (53).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (54).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (55).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (56).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (57).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (58).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (59).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (60).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (61).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (62).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (63).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (64).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (65).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (66).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (67).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (68).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (69).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (70).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (71).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (72).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (73).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (74).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (75).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (76).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (77).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (78).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (79).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (80).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (81).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (82).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (83).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (84).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (85).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (86).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (87).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (88).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (89).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (90).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (91).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (92).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (93).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (94).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (95).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (96).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (97).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (98).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (99).png","tipos":["Dimnit"]},
    {"nome":"Dimnit (100).png","tipos":["Dimnit"]},
    {"nome":"Nazli (1).png","tipos":["Nazli"]},
    {"nome":"Nazli (2).png","tipos":["Nazli"]},
    {"nome":"Nazli (3).png","tipos":["Nazli"]},
    {"nome":"Nazli (4).png","tipos":["Nazli"]},
    {"nome":"Nazli (5).png","tipos":["Nazli"]},
    {"nome":"Nazli (6).png","tipos":["Nazli"]},
    {"nome":"Nazli (7).png","tipos":["Nazli"]},
    {"nome":"Nazli (8).png","tipos":["Nazli"]},
    {"nome":"Nazli (9).png","tipos":["Nazli"]},
    {"nome":"Nazli (10).png","tipos":["Nazli"]},
    {"nome":"Nazli (11).png","tipos":["Nazli"]},
    {"nome":"Nazli (12).png","tipos":["Nazli"]},
    {"nome":"Nazli (13).png","tipos":["Nazli"]},
    {"nome":"Nazli (14).png","tipos":["Nazli"]},
    {"nome":"Nazli (15).png","tipos":["Nazli"]},
    {"nome":"Nazli (16).png","tipos":["Nazli"]},
    {"nome":"Nazli (17).png","tipos":["Nazli"]},
    {"nome":"Nazli (18).png","tipos":["Nazli"]},
    {"nome":"Nazli (19).png","tipos":["Nazli"]},
    {"nome":"Nazli (20).png","tipos":["Nazli"]},
    {"nome":"Nazli (21).png","tipos":["Nazli"]},
    {"nome":"Nazli (22).png","tipos":["Nazli"]},
    {"nome":"Nazli (23).png","tipos":["Nazli"]},
    {"nome":"Nazli (24).png","tipos":["Nazli"]},
    {"nome":"Nazli (25).png","tipos":["Nazli"]},
    {"nome":"Nazli (26).png","tipos":["Nazli"]},
    {"nome":"Nazli (27).png","tipos":["Nazli"]},
    {"nome":"Nazli (28).png","tipos":["Nazli"]},
    {"nome":"Nazli (29).png","tipos":["Nazli"]},
    {"nome":"Nazli (30).png","tipos":["Nazli"]},
    {"nome":"Nazli (31).png","tipos":["Nazli"]},
    {"nome":"Nazli (32).png","tipos":["Nazli"]},
    {"nome":"Nazli (33).png","tipos":["Nazli"]},
    {"nome":"Nazli (34).png","tipos":["Nazli"]},
    {"nome":"Nazli (35).png","tipos":["Nazli"]},
    {"nome":"Nazli (36).png","tipos":["Nazli"]},
    {"nome":"Nazli (37).png","tipos":["Nazli"]},
    {"nome":"Nazli (38).png","tipos":["Nazli"]},
    {"nome":"Nazli (39).png","tipos":["Nazli"]},
    {"nome":"Nazli (40).png","tipos":["Nazli"]},
    {"nome":"Nazli (41).png","tipos":["Nazli"]},
    {"nome":"Nazli (42).png","tipos":["Nazli"]},
    {"nome":"Nazli (43).png","tipos":["Nazli"]},
    {"nome":"Nazli (44).png","tipos":["Nazli"]},
    {"nome":"Nazli (45).png","tipos":["Nazli"]},
    {"nome":"Nazli (46).png","tipos":["Nazli"]},
    {"nome":"Nazli (47).png","tipos":["Nazli"]},
    {"nome":"Nazli (48).png","tipos":["Nazli"]},
    {"nome":"Nazli (49).png","tipos":["Nazli"]},
    {"nome":"Nazli (50).png","tipos":["Nazli"]},
    {"nome":"Nazli (51).png","tipos":["Nazli"]},
    {"nome":"Nazli (52).png","tipos":["Nazli"]},
    {"nome":"Nazli (53).png","tipos":["Nazli"]},
    {"nome":"Nazli (54).png","tipos":["Nazli"]},
    {"nome":"Nazli (55).png","tipos":["Nazli"]},
    {"nome":"Nazli (56).png","tipos":["Nazli"]},
    {"nome":"Nazli (57).png","tipos":["Nazli"]},
    {"nome":"Nazli (58).png","tipos":["Nazli"]},
    {"nome":"Nazli (59).png","tipos":["Nazli"]},
    {"nome":"Nazli (60).png","tipos":["Nazli"]},
    {"nome":"Nazli (61).png","tipos":["Nazli"]},
    {"nome":"Nazli (62).png","tipos":["Nazli"]},
    {"nome":"Nazli (63).png","tipos":["Nazli"]},
    {"nome":"Nazli (64).png","tipos":["Nazli"]},
    {"nome":"Nazli (65).png","tipos":["Nazli"]},
    {"nome":"Nazli (66).png","tipos":["Nazli"]},
    {"nome":"Nazli (67).png","tipos":["Nazli"]},
    {"nome":"Nazli (68).png","tipos":["Nazli"]},
    {"nome":"Nazli (69).png","tipos":["Nazli"]},
    {"nome":"Nazli (70).png","tipos":["Nazli"]},
    {"nome":"Nazli (71).png","tipos":["Nazli"]},
    {"nome":"Nazli (72).png","tipos":["Nazli"]},
    {"nome":"Nazli (73).png","tipos":["Nazli"]},
    {"nome":"Nazli (74).png","tipos":["Nazli"]},
    {"nome":"Nazli (75).png","tipos":["Nazli"]},
    {"nome":"Nazli (76).png","tipos":["Nazli"]},
    {"nome":"Nazli (77).png","tipos":["Nazli"]},
    {"nome":"Nazli (78).png","tipos":["Nazli"]},
    {"nome":"Nazli (79).png","tipos":["Nazli"]},
    {"nome":"Nazli (80).png","tipos":["Nazli"]},
    {"nome":"Nazli (81).png","tipos":["Nazli"]},
    {"nome":"Nazli (82).png","tipos":["Nazli"]},
    {"nome":"Nazli (83).png","tipos":["Nazli"]},
    {"nome":"Nazli (84).png","tipos":["Nazli"]},
    {"nome":"Nazli (85).png","tipos":["Nazli"]},
    {"nome":"Nazli (86).png","tipos":["Nazli"]},
    {"nome":"Nazli (87).png","tipos":["Nazli"]},
    {"nome":"Nazli (88).png","tipos":["Nazli"]},
    {"nome":"Nazli (89).png","tipos":["Nazli"]},
    {"nome":"Nazli (90).png","tipos":["Nazli"]},
    {"nome":"Nazli (91).png","tipos":["Nazli"]},
    {"nome":"Nazli (92).png","tipos":["Nazli"]},
    {"nome":"Nazli (93).png","tipos":["Nazli"]},
    {"nome":"Nazli (94).png","tipos":["Nazli"]},
    {"nome":"Nazli (95).png","tipos":["Nazli"]},
    {"nome":"Nazli (96).png","tipos":["Nazli"]},
    {"nome":"Nazli (97).png","tipos":["Nazli"]},
    {"nome":"Nazli (98).png","tipos":["Nazli"]},
    {"nome":"Nazli (99).png","tipos":["Nazli"]},
    {"nome":"Nazli (100).png","tipos":["Nazli"]}
]

listaPastas = [
    {"nome":"Ak",
     "sigla":"Ak",
     "numero": 0},
    {"nome":"Ala_Idris",
     "sigla":"Ala_Idris",
     "numero": 1},
    {"nome":"Buzgulu", 
     "sigla":"Buzgulu",
     "numero": 2},
    {"nome":"Dimnit",
     "sigla":"Dimnit",
     "numero": 3},
    {"nome":"Nazli",
     "sigla":"Nazli",
     "numero": 4}
]

listaPastas2 = [
    {"nome":"Ak",
     "sigla":"Ak",
     "numero": 0},
    {"nome":"Ala_Idris",
     "sigla":"Ala_Idris",
     "numero": 1},
    {"nome":"Buzgulu", 
     "sigla":"Buzgulu",
     "numero": 2},
    {"nome":"Dimnit",
     "sigla":"Dimnit",
     "numero": 3},
    {"nome":"Nazli",
     "sigla":"Nazli",
     "numero": 4}
]

import os
import shutil
import random

random.shuffle(imagens)
setenta_porcento = int(len(imagens)*0.70)
vinte_e_cinco_porcento = int(len(imagens)*0.25)
imagens_train = imagens[0:setenta_porcento]
imagens_test = imagens[setenta_porcento:(setenta_porcento+vinte_e_cinco_porcento)]
imagens_val = imagens[(setenta_porcento+vinte_e_cinco_porcento):]
source_dir = "imagens"

folder_name_train = "train"
folder_name_test = "test"
folder_name_val = "val"
os.makedirs(folder_name_train, exist_ok=True)
os.makedirs(folder_name_test, exist_ok=True)
os.makedirs(folder_name_val, exist_ok=True)

for pasta in listaPastas2:
    folder_name = f"{pasta['sigla']}"
    folder_path = os.path.join(folder_name_train, folder_name)
    os.makedirs(folder_path, exist_ok=True)
for pasta in listaPastas2:
    folder_name = f"{pasta['sigla']}"
    folder_path = os.path.join(folder_name_test, folder_name)
    os.makedirs(folder_path, exist_ok=True)
for pasta in listaPastas2:
    folder_name = f"{pasta['sigla']}"
    folder_path = os.path.join(folder_name_val, folder_name)
    os.makedirs(folder_path, exist_ok=True)

for foto in imagens_test:
    src_file = os.path.join(source_dir, foto["nome"])
    for pasta in listaPastas2:
        if any(tipos in [pasta["nome"]] for tipos in foto["tipos"]):
            dest_folder = f'{pasta["sigla"]}'
            dest_path = os.path.join(folder_name_test, dest_folder)
            shutil.copy2(src_file, dest_path)
            break
for foto in imagens_val:
    src_file = os.path.join(source_dir, foto["nome"])
    for pasta in listaPastas2:
        if any(tipos in [pasta["nome"]] for tipos in foto["tipos"]):
            dest_folder = f'{pasta["sigla"]}'
            dest_path = os.path.join(folder_name_val, dest_folder)
            shutil.copy2(src_file, dest_path)
            break
for foto in imagens_train:
    src_file = os.path.join(source_dir, foto["nome"])
    for pasta in listaPastas2:
        if any(tipos in [pasta["nome"]] for tipos in foto["tipos"]):
            dest_folder = f'{pasta["sigla"]}'
            dest_path = os.path.join(folder_name_train, dest_folder)
            shutil.copy2(src_file, dest_path)
            break